### ISSUE TITLE
Update components to use properties

### ISSUE THREAD

**Issue by stackingsaunter** [GBKS/bitcoin-wallet-ui-kit#10] opened 2022-08-07 19:08 UTC
Hi there!

I propose utilising more properties within the guide, which I guess will affect mostly buttons but can be also in other components like lists or dropdowns, etc. I recorded [a quick video about this](https://www.youtube.com/watch?v=lE4rK-wIHc4).

In short, using more properties instead of variants will:
- make it easier and quicker to edit components
- make it easier and quicker to use components, modify variants depending on a case
- will allow for more flexible usage with less variants
- (supposedly) is more suitable for handoff

**Comment by GBKS** [comment] 2022-08-08 20:26
Already on it, sir. The last version of the UI Kit [published on July 29](https://www.figma.com/community/file/916680391812923706) already has most components updated to use properties. There were a few nice effects like needing much fewer variants for certain components, as showing/hiding could be done via Boolean properties.

**Comment by jakubszwedo** [comment] 2022-08-08 22:02
Sweet! I still see a lot of possibilities to improve what I see in that file, I'd be happy to help with these

**Comment by GBKS** [comment] 2022-08-09 05:53
Great. Would love to know what you'd change.

**Comment by jakubszwedo** [comment] 2022-08-11 22:24
So first of all there is a button component as I laid out in the video. In case we really want to show all possible states of the component we can show them separately like here (I used Propstar plugin to generate that table):
<img width="1458" alt="Screenshot 2022-08-12 at 00 16 26" src="https://user-images.githubusercontent.com/68239231/184251821-a2a5dc41-8a6b-4b95-8d5a-4455f826d240.png">

Label component can be done into one (maybe two) highly adjustable components, with each of the element having the possibility to be turned off/on, and adding Copy property 
<img width="363" alt="Screenshot 2022-08-12 at 00 19 12" src="https://user-images.githubusercontent.com/68239231/184252148-8fb4709a-7d71-4fbc-b9c8-3a3f1825730c.png">


Lot's of those can be merged
<img width="434" alt="Screenshot 2022-08-12 at 00 21 12" src="https://user-images.githubusercontent.com/68239231/184252366-c455df2a-9035-4ae3-a19c-51ee60c02838.png">
<img width="531" alt="Screenshot 2022-08-12 at 00 23 19" src="https://user-images.githubusercontent.com/68239231/184252569-5f8811c2-849a-464c-8ff9-da992717cecb.png">
<img width="376" alt="Screenshot 2022-08-12 at 00 23 33" src="https://user-images.githubusercontent.com/68239231/184252596-3d5f85af-09f7-4591-a37a-def8c9fd956a.png">

Inputs can be expanded into more states (active, filled, focused, error, maybe confirmed (positive feedback)
<img width="313" alt="Screenshot 2022-08-12 at 00 21 52" src="https://user-images.githubusercontent.com/68239231/184252421-9b774d25-5b50-4258-a251-c63113eff3cc.png">

I see some space for expansion of new elements, like toast messages for example, or other classic UI elements that are missing. Let me know what you think! I'll be happy to work on those

**Comment by GBKS** [comment] 2022-08-15 07:23
Thanks for this. Some quick responses:

- Yes, the "List item" component can be removed. There already is a new component just called "Item", I just haven't gone through the file and done the clean-up yet.
- Something I've been wanting to clean up is the uneven spacing in buttons. Since icons have some white space around them, the space on the side of the icon is wider than on the side of the label. With a boolean property, we could also toggle an invisible spacer to balance this out.
- As you pointed out, now that some elements can be hidden, the component itself becomes simpler, but you need this extra display to showcase all the options for designers. Weird how that turned out.
- Field states are something we should add.
- As far as new elements go, I've only been adding ones I actually end up needing during design work. That has helped keep things efficient.

**Comment by GBKS** [comment] 2023-11-23 15:25
Going to close this issue as it's gone stale. The states have their separate issue via #18.

**Closed by GBKS** 2023-11-23 15:25 UTC
